### PR TITLE
Regex Filtering of SFTPCopy Files

### PR DESCRIPTION
**Pull request by gokulavasan**

### CODE REVIEW

**Comment by sreevatsanraman** [comment]
Need to bump the version.

**Comment by gokulavasan** [comment]
@sreevatsanraman Can you advise on the next version? Should it be 1.1.0-SNAPSHOT?

**Comment by sreevatsanraman** [comment]
1.1.0

**Comment by sreevatsanraman** [comment]
LGTM. Let's update this to cask market and remove the older version of SFTP actions

**Pull request merged**
